name: Trunk branch release
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - ".github/**"
jobs:
  generateVersion:
    name: "Generate release"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate version
        id: generate-version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: ""
          format: "${major}.${minor}.${patch}"

          